### ISSUE TITLE
Feature Request: Badges should link to their commits/PRs/issues

### ISSUE THREAD

**Issue by JarredAllen** [my-badges/my-badges#37]
Many of the badges relate to having done some commit, PR, or issue with some properties. I think it'd be neat if those badges could be made such that they link to the commit, etc. that unlocked the badge. The link already appears in the CI Action logs, but it'd be more convenient and fun imo if the links were more accessible.

I'm not sure how to handle the badges that relate to multiple commits (e.g. the fix chain badges), and there's probably not anything useful link you can make for some (e.g. the account has been around for X years badges), but I think it'd be cool if the ones that can have a good link are made to do that.

**Comment by antonmedv** [comment]
Ghis is actually how badges work now. You can click on any badge and you will see list of commits/issues/pr.

**Comment by JarredAllen** [comment]
Oh, my bad. I looked somewhere and saw the link only had the image and not the list, but I see it actually works like this and I can't even find what I was looking at originally.

**Comment by antonmedv** [comment]
The list with images was in the readme at the beginning. But I decided to hide list of all images, to make it more interesting to discover new badges)
