### ISSUE TITLE
Didn’t find the chore commit, although it exists

### ISSUE THREAD

**Issue by andrewjswan** [my-badges/my-badges#43]
Didn’t find the chore commit, although it exists:
https://github.com/andrewjswan/esphome-config/commit/c8d49ad23958e7fe2654af1a7fe5b7a1923353de

**Comment by antonmedv** [comment]
It looks for `^chore:` regexp =)

**Comment by andrewjswan** [comment]
Why didn’t find it here?
https://github.com/andrewjswan/EspHoMaTriXv2/commit/92274919f99d383c30a9a047ee8608cae37acb32

**Comment by antonmedv** [comment]
Difficult to tell. First check if action is successful and you can see your repo in logs.

**Comment by andrewjswan** [comment]
Its search only in main branches ...
