### ISSUE TITLE
[BUG] My favorite word chooses `-` as a word, although `-` is not a word

### ISSUE THREAD

**Issue by andrewjswan** [my-badges/my-badges#45]
My favorite word chooses `-` as a word, although `-` is not a word, can it be removed?
```
- (used 837 times)
```

**Comment by andrewjswan** [comment]
If we remove all words less than or equal to 1 letter, the result, in my opinion, will be more correct.
https://github.com/my-badges/my-badges/blob/6601d49aef11244480b7ebe54965729eab5338af/src/all-badges/favorite-word/favorite-word.ts#L14

Current solution for message: **test a message - test - MP1-3345: commit message**
Return:
```
[LOG]: "My favorite commit message words are:

1. test (used 2 times)
2. message (used 2 times)
3. - (used 2 times)
4. a (used 1 times)
5. mp1-3345: (used 1 times)" 
```
My solution return:
```
[LOG]: "My favorite commit message words are:

1. test (used 2 times)
2. message (used 2 times)
3. mp1-3345: (used 1 times)
4. commit (used 1 times)" 
```

**Comment by qoomon** [comment]
To filter stop-words would be even better I think. 
Should be easy to implement with https://www.npmjs.com/package/stopword

**Comment by andrewjswan** [comment]
In my opinion, a word with one letter is not very informative, so this solution is quite workable. Stop words can weed out the superfluous, but who knows who has it and what kind of superfluous it is.

**Comment by andrewjswan** [comment]
It appeared again:
https://github.com/andrewjswan/andrewjswan/commit/c68b60025dbd1b8205a4d275d15bda5ae6d1de3e
```
My favorite commit message words are:

1. add (used 996 times)
2. - (used 808 times)
3. update (used 696 times)
4. merge (used 506 times)
5. fix (used 401 times)
```

**Comment by antonmedv** [comment]
=)))
