### ISSUE TITLE
"my profile" link is dead

### ISSUE THREAD

**Issue by landfillbaby** [my-badges/my-badges#5]
https://github.com/antonmedv 404s as of yesterday. but you've committed here since then.
where did fx and walk's source code go?
https://github.com/termux/termux-packages/issues/18175

**Comment by tomahand** [comment]
@antonmedv got blocked on GitHub, we trying to restore his account.

**Comment by ckujau** [comment]
Apparently @antonmedv is back on Github, and so is `fx`, yay! :-)

**Comment by antonmedv** [comment]
Yeap)sorry for inconvenience.
