### ISSUE TITLE
Question: Morning Commits

### ISSUE THREAD

**Issue by andrewjswan** [my-badges/my-badges#51]
I can’t understand how morning commits are counted.
I made a commit this morning, Github wrote in the patch: `Date: Tue, 13 Feb 2024 07:35:15 +0200`, but the commit is not protected in the badge.
https://github.com/andrewjswan/SwatchTime/commit/580e2fc26eb00acf878a95366ca5b544482db031

**Comment by andrewjswan** [comment]
My location Ukraine: 
https://github.com/my-badges/my-badges/blob/4f50c1c2970693c52358fb0da1ca9c19eadc384c/src/all-badges/time-of-commit/time-of-commit.ts#L106
But `07:35:15` in UTC its `07:35:15` - `3` = `04:35:15`
It should have been found, 
https://github.com/my-badges/my-badges/blob/4f50c1c2970693c52358fb0da1ca9c19eadc384c/src/all-badges/time-of-commit/time-of-commit.ts#L20-L22
But it didn’t, so is this a bug?

**Comment by andrewjswan** [comment]
Or, on the contrary, TZ is added to the time that Github gives?
https://github.com/my-badges/my-badges/blob/4f50c1c2970693c52358fb0da1ca9c19eadc384c/src/all-badges/time-of-commit/time-of-commit.ts#L18
Ie `07:35:15` + `3` = `10:35:15` ?
Or `07:35:15 +0200` + `3` = `12:35:15` or `8:35:15` ???
I don’t quite understand this time calculation.

**Comment by antonmedv** [comment]
Try! TZ calculation are odd ¯\\\_(ツ)_/¯ You can try to debug it locally.

**Comment by andrewjswan** [comment]
> You can try to debug it locally.

How?



> True! TZ calculation are odd ¯\_(ツ)_/¯

It all depends on the algorithm, I don’t understand it well, why add TZ to compare with UTC?

**Comment by andrewjswan** [comment]
Look like I found error:
```
const date1 = new Date('December 31, 1975, 23:15:30 GMT+11:00');
console.log(date1.getUTCHours());
// Return: 12 - Ok
```
But
```
const date1 = new Date('December 31, 1975, 23:15:30 GMT+11:00');
date1.setHours(date1.getUTCHours() + 3)
console.log(date1.getUTCHours());
// Return: 12 - Not Ok!
```
And
```
const date1 = new Date('December 31, 1975, 23:15:30 GMT+11:00');
date1.setUTCHours(date1.getUTCHours() + 3)
console.log(date1.getUTCHours());
// Return: 15 - Ok!
```
Test:  [TS Play](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAJgQygUwIwwLwzMg7jAESWQAoByA5YZAWwCNkAnGAZlQBoZUBOAdgFZOAJhYAuVP1EsADDADiAWQAqAalSpR06WQCUAbgBQoSCAA2yAHSmQAcxIAiAKIAPAA5UUcGCACuUV36iXEIwALQw9jAq8MSoFjbIUACqSgDCABK+jBAkOvoGAPQFMC7uwJ7efgFQQahCBkbg0DEoIVg4+EQo5JTU9EysHFx8gjAi4pIy8spqGlq6hoitFhCJmT7ZJEvIQvGJKRlZOTpRrDqNJuZWtg6lHshevv6BXPxhEafbuwnJaeubeUMRRKbnujyqLwkDWMzW2LEw2DwhGIPSotAYzDYnB4AmEYgkUlkilU6k02nycJW+z+Ry2xBYe1+hw2x1OLHOMLMlmsdicoPKD0qzxqr3ekWilJ+B3+x3ywLuAvBwtq9QMQA)

PS: I make PR

**Comment by andrewjswan** [comment]
@antonmedv Thanks, that's better. :)

One more question remains: isn't it too early in the morning? Still, from 4 to 6... a little early in my opinion. 
https://github.com/my-badges/my-badges/blob/4f50c1c2970693c52358fb0da1ca9c19eadc384c/src/all-badges/time-of-commit/time-of-commit.ts#L20-L22
How do you think.

**Comment by antonmedv** [comment]
Morning is very резиновый term. My idea for this badge was: very morning. Not just usual-morning (some people start working at 8 altready), but rather very unusual morning.

**Comment by andrewjswan** [comment]
4 hours, in my opinion this is night :) But I understood the idea, then I close the PR, although 7 am is still early morning in my opinion.4 hours, in my opinion this is night :) But I understood the idea, then I close the PR, although 7am+ is still early morning in my opinion. :)

**Comment by andrewjswan** [comment]
I looked at the ideas and found this one: **sleepy-coder** - For commits made in the very early hours of the morning. 
But it turns out that we can make it, or we just made it. Then morning needs to be changed to morning.
Or was there some other idea?

**Comment by antonmedv** [comment]
sleepy-coder sounds good)

**Comment by antonmedv** [comment]
ChatGPT can help with drawing)

**Comment by andrewjswan** [comment]
> ChatGPT can help with drawing)

It seems I don’t know how to cook him, he always draws me some kind of nonsense :)

**Comment by andrewjswan** [comment]
This is the best option for now, I'll try to make a sticker out of it.
![image](https://github.com/my-badges/my-badges/assets/3609660/9311ae85-48d6-4824-9a3e-ef42f5440422)

**Comment by andrewjswan** [comment]
Is the time right? Or do I need to change it?

**Comment by antonmedv** [comment]
Try to ask somethink like this:

    A sticker of a panda, white background.

**Comment by andrewjswan** [comment]
> Try to ask somethink like this:

I read the documentation :) and that's where I started.

**Comment by andrewjswan** [comment]
Looks like I've done it, updated PR#51

**Comment by andrewjswan** [comment]
Fixed...

**Comment by antonmedv** [comment]
@andrewjswan what about this image?
![DALL·E 2024-02-23 15 24 42 - A round sticker design featuring a sleepy programmer  The programmer is depicted as a cute, cartoonish figure with exaggerated tired eyes, sitting at ](https://github.com/my-badges/my-badges/assets/141232/43dda84d-4c8f-402f-9422-6500a5bc827e)

**Comment by andrewjswan** [comment]
He looks more like a patient, or a tear-stained person, or he has completely erased the repository and all its copies, which should be put into production tomorrow. :)
