### ISSUE TITLE
[BUG]: Failed to load issue timeline, due to missing pageInfo property

### ISSUE THREAD

**Issue by qoomon** [my-badges/my-badges#61]
All timeline request fails because of the missing pageInfo property in the graphql response

error example:
```
Loading issue timeline for XXX#123
Failed to load issue timeline for XXX#123
MissingPageInfo: No pageInfo property found in response. Please make sure to specify the pageInfo in your query. Response-Data: 
...
```

**Comment by andrewjswan** [comment]
+1

**Comment by Azecko** [comment]
I got the same problem, any news about it ?
But I can't figure out if the badges are working or not, because it still updates my badges. ???

**Comment by antonmedv** [comment]
Hmmm, looks like we need a way to be able to asynchronously load badges.

**Comment by antonmedv** [comment]
Should be fixed!

**Comment by Azecko** [comment]
Yeah, looks like it is fixed. I think the issue can be closed.
