### ISSUE TITLE
[FR] Ugly Badge for Cosmetic commits

### ISSUE THREAD

**Issue by qoomon** [my-badges/my-badges#62]
The cosmetic badge is so ugly in comparison to all the other beautiful badges.
Please replace it withe a badge matching the other badges style.

Source: https://github.com/my-badges/my-badges/blob/master/src/all-badges/cosmetic-commit/cosmetic-commit.png
![image](https://github.com/my-badges/my-badges/assets/3963394/58c6a376-7204-4db7-bb42-71521b925959)

**Comment by qoomon** [comment]
love it

**Comment by andrewjswan** [comment]
Great! But it seems to me better to remove the background, make it round like the others.

**Comment by qoomon** [comment]
![cosmetig-badge](https://github.com/my-badges/my-badges/assets/3963394/29c5910f-9397-4abd-9616-c9276cb76e4f)

**Comment by qoomon** [comment]
It looks so much better now, thx
