### ISSUE TITLE
Would achievements related to a specific repo be possible and/or allowed?

### ISSUE THREAD

**Issue by bdeadman** [my-badges/my-badges#69]
Thanks for contributing this to the community.

I'm part of an open-source science initiative ([Open Reaction Database](https://github.com/open-reaction-database)) which uses a GitHub repo to archive data which is provided by the community. We are thinking of ways to recognise our contributors and the idea of GitHub badges came up recently. 

First Question: Would the my-badges team be interested in having achievements which are linked to specific repos? I can see why this might go against what you had in mind for my-badges. Perhaps you would prefer such specific badges to be made in a fork?

Second Question: Do you think it is technically feasible to create an achievement linked to a specific repo? At a glance, it looks like it will be beyond my abilities (chemist turned amateur Python coder) but I may be able to get one of our supporting developers to do some of the "heavy lifting". Any pointers would be greatly appreciated.

**Comment by antonmedv** [comment]
> First Question: Would the my-badges team be interested in having achievements which are linked to specific repos? I can see why this might go against what you had in mind for my-badges. Perhaps you would prefer such specific badges to be made in a fork?

It is ok. More badges are better. 

> Second Question: Do you think it is technically feasible to create an achievement linked to a specific repo? At a glance, it looks like it will be beyond my abilities (chemist turned amateur Python coder) but I may be able to get one of our supporting developers to do some of the "heavy lifting". Any pointers would be greatly appreciated.

it is totally doable
