### ISSUE TITLE
`spooky-commit` was not added

### ISSUE THREAD

**Issue by andrewjswan** [my-badges/my-badges#71]
`spooky-commit` was not added, the commit was made on 10/31/2024, but for some reason, the badge was not added.
commit: https://github.com/andrewjswan/svitlobot/commit/1cccefbf36463a6cde1c730fe5107bf2011adf02.patch
action: https://github.com/andrewjswan/andrewjswan/actions/runs/11622110394/job/32367041283#step:2:118
my badges commit: https://github.com/andrewjswan/andrewjswan/commit/1dbdf3ba610f7001e7187f32fa60735cce67befb

**Comment by andrewjswan** [comment]
https://api.github.com/repos/andrewjswan/svitlobot/commits
```
"commit": {
      "author": {
        "name": "Andrew J.Swan",
        "email": "ajs.blackhole@gmail.com",
        "date": "2024-10-31T12:42:48Z"
      },
      "committer": {
        "name": "Andrew J.Swan",
        "email": "ajs.blackhole@gmail.com",
        "date": "2024-10-31T12:42:48Z"
      },
      "message": "Fix for ESPHome 2024.10",
      "tree": {
        "sha": "d9dfa98f8978860993a38604978b0e055bdc7e11",
        "url": "https://api.github.com/repos/andrewjswan/svitlobot/git/trees/d9dfa98f8978860993a38604978b0e055bdc7e11"
      },
      "url": "https://api.github.com/repos/andrewjswan/svitlobot/git/commits/1cccefbf36463a6cde1c730fe5107bf2011adf02",
      "comment_count": 0,
      "verification": {
        "verified": false,
        "reason": "unsigned",
        "signature": null,
        "payload": null
      }
```

**Comment by antonmedv** [comment]
I see. Let's fix it!

**Comment by VatsalSy** [comment]
+1 ..

**Comment by andrewjswan** [comment]
I support it, but I don’t know `ts`, and I still don’t understand how it works now, and why this badge isn’t added.

**Comment by andrewjswan** [comment]
We are looking forward... :)

**Comment by andrewjswan** [comment]
Hi!

Any news? :)

**Comment by andrewjswan** [comment]
@antonmedv I looked through the entire code several times, went through the chain, and still didn't understand why it doesn't work. Maybe you can give me a hint as to why, maybe I'll understand and make a PR?

**Comment by antonmedv** [comment]
Ufff! I had to put **a lot** of efforts to fix it))) 

https://github.com/my-badges/my-badges/commit/88a1fde91123cd38a31b5d7562306395d3d45d39

**Comment by antonmedv** [comment]
Please check it. Should be fixed now!

**Comment by VatsalSy** [comment]
I might be wrong here but doesn't typeset work with 0 index counting and not 1? 

so or 31st oct, it should be: if (data.getMonth() === 9 && data.getDate() === 31) {...}

instead of if (data.getMonth() === 10 && data.getDate() === 31) {...}

regarding: https://github.com/my-badges/my-badges/blob/master/badges/spooky-commit/spooky-commit.ts

**Comment by antonmedv** [comment]
True! getMonth is 0-based: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth

Could you do a fix?

**Comment by VatsalSy** [comment]
yes. on it.. :)

**Comment by VatsalSy** [comment]
testing was longer than editing.. but there you go: #73

**Comment by andrewjswan** [comment]
Thanks! Worked! :)
